name: Deployment (Container)

on:
  push:
    branches:
      - main
      - dev
      - master

env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest

    container:
      image: node:16

    services:
      mongodb:
        image: mongo:5
        # ports:
        #   - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_DB_NAME: gha-demo
      MONGODB_CLUSTER_ADDRESS: mongodb # This name comes from the `services` key
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
      PORT: 8080

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Start server
        run: npm start & npx wait-on http://127.0.0.1:$PORT

      - name: Run tests
        run: npm test

      - name: Output information
        run: |
          echo "MongoDB Protocol: $MONGODB_CONNECTION_PROTOCOL"
          echo "MongoDB Host: $MONGODB_CLUSTER_ADDRESS"
          echo "MongoDB Username: $MONGODB_USERNAME"
          echo "MongoDB DB Name: $MONGODB_DB_NAME"
