jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest

    container:
      image: node:16

    services:
      mongodb:
        image: mongo:5

        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_DB_NAME: gha-demo
      MONGODB_CLUSTER_ADDRESS: mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
      PORT: 8080

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT

      - name: Run tests
        run: npm test

      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
